# Generated by Django 3.1.5 on 2021-01-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nLab', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField()),
                ('exits', models.IntegerField()),
                ('exit_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exit_reach', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reservoil', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Tipo 1'), (1, 'Tipo 2'), (2, 'Tipo 3')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MachineVeclocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('march', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('accuracy', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('clinicalAnalysi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinicalanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('seed', models.CharField(blank=True, max_length=100, null=True)),
                ('activities', models.ManyToManyField(to='api.Activity')),
                ('collections', models.ManyToManyField(to='api.SamplingPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField()),
                ('type', models.IntegerField(choices=[(0, 'Tipo 1'), (1, 'Tipo 2'), (2, 'Tipo 3')], default=0)),
                ('fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipments', models.ManyToManyField(to='api.MachineEquipment')),
                ('velocitys', models.ManyToManyField(to='api.MachineVeclocity')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machines', models.ManyToManyField(to='api.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('machines', models.ManyToManyField(to='api.Machine')),
                ('plantings', models.ManyToManyField(to='api.MachineEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cnpj', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
    ]
