# Generated by Django 3.1.5 on 2021-01-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
    ]
