# Generated by Django 3.1.5 on 2021-01-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_farm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='farm',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.owner'),
        ),
    ]
