# Generated by Django 3.1.5 on 2021-01-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210123_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='equipments',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='velocitys',
        ),
        migrations.AddField(
            model_name='machineequipment',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine'),
        ),
        migrations.AddField(
            model_name='machineveclocity',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine'),
        ),
    ]
