# Generated by Django 3.1.5 on 2021-01-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210123_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='plantings',
        ),
        migrations.AddField(
            model_name='machine',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.farm'),
        ),
        migrations.AddField(
            model_name='planting',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.farm'),
        ),
    ]
