# Generated by Django 3.1.5 on 2021-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210123_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
