# Generated by Django 3.1.5 on 2021-02-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210127_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplingpoint',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='samplingpoint',
            old_name='lng',
            new_name='longitude',
        ),
    ]
