# Generated by Django 3.1.5 on 2021-02-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210203_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplingpoint',
            old_name='date',
            new_name='startDate',
        ),
        migrations.AddField(
            model_name='planting',
            name='grid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
