# Generated by Django 3.1.5 on 2021-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210203_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplingpoint',
            old_name='startDate',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='grid',
        ),
        migrations.AddField(
            model_name='samplingpoint',
            name='grid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
