# Generated by Django 3.1.5 on 2021-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_plantingarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingpoint',
            name='compaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
