# Generated by Django 3.1.5 on 2021-02-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210211_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingpoint',
            name='compaction',
        ),
        migrations.CreateModel(
            name='CompactionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('depth', models.IntegerField(null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('SamplingPoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.samplingpoint')),
            ],
        ),
    ]
